# In case you have problems with node, npm, webpack, you can use docker to make a separate "machine"
# https://docs.docker.com/get-docker/

# Run this command:
# docker-compose up

version: "3.2"
services:
  webpack:
    build: .
    container_name: PokeMe
    ports:
      - "8080:8080"
    volumes:
      - ./:/poke-me
      - ignore:/poke-me/node_modules 
volumes:
  ignore: {}